import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar"
import Footer from "@/component/Footer";
import NextAuthProvider from "@/provider/NextAuthProvider";
// import Providers from "./providers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Devel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >

          <header className="">
            <Navbar></Navbar>
          </header>

          {children}

          <Footer></Footer>
        </body>
      </html>
    </NextAuthProvider>
  );
}
